#!/bin/sh

# this file is run when calling startx

# default arch init scripts
#if [ -d /etc/X11/xinit/xinitrc.d ]; then
#    for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
#        [ -x "$f" ] && . "$f"
#    done
#fi

# user init scripts and settings
#[ -r /etc/X11/xinit/.Xmodmap ] && xmodmap /etc/X11/xinit/.Xmodmap
#[ -r ~/.Xmodmap ] && xmodmap ~/.Xmodmap
#[ -r ~/.Xresources ] && xrdb -merge ~/.Xresources
#[ -r ~/.xprofile ] && . ~/.xprofile
~/.local/bin/battery.sh &
tint2 &
#nm-applet &
pulseaudio -k &
pkill -9 pulseaudio &
pulseaudio --start &
pulseaudio --disallow-exit --disable-shm &
pulseaudio --start &
start-pulseaudio-x11 &
amixer -c 0 set Master playback 100% unmute && volumeicon &
pactl set-sink-volume 0 100% &
pactl set-sink-volume 0 100% && ksuperkey -e 'Super_L=Alt_L|F1' &
pactl set-sink-volume 0 100% && ksuperkey -e 'Super_R=Alt_L|F1' &
amixer -c 0 set Master playback 100% unmute && nitrogen --restore &
amixer -c 0 set Master playback 100% unmute &
amixer -c 0 set Master playback 100% unmute &
pactl set-sink-volume 0 100% &
# launch the session, commands below this line will be ignored
amixer -c 0 set Master playback 100% unmute &
cd ~/.local/songs/
export beep=~/.local/songs/maria.ogg
pactl upload-sample ~/.local/songs/maria.ogg
paplay "$beep" --volume=76767 &
cd ~/
exec openbox
